name: "Install Verible"
description: "Install Verible release"

inputs:
  github_token:
    description: 'GITHUB_TOKEN'
    default: ''
  verible_version:
    description: 'Use selected Verible version (defaults to latest release)'
    default: 'latest'

runs:
  using: "composite"
  steps:
    - name: Install dependencies
      shell: bash
      run: |
          sudo apt install curl jq wget
    - name: Download and unpack Verible
      shell: bash
      run: |
          mkdir verible
          if [ "${{ inputs.verible_version }}" = "latest" ]; then
            VERIBLE_RELEASES_JSON=$(curl --header 'authorization: Bearer ${{ inputs.github_token }}' -fsSL https://api.github.com/repos/bradatqci/verible-linter-action/releases/latest)
            VERIBLE_TARBALL=$(echo $VERIBLE_RELEASES_JSON | jq -r '.assets[] | select(.browser_download_url | test("(?=.*Ubuntu-22.04)(?=.*x86_64)")).browser_download_url')
          else
            VERIBLE_TARBALL="https://github.com/bradatqci/verible-linter-action/releases/download/${{ inputs.verible_version }}/verible-${{ inputs.verible_version }}-Ubuntu-22.04-focal-x86_64.tar.gz"
          fi
          echo "Downloading $VERIBLE_TARBALL"
          wget -qO- $VERIBLE_TARBALL | tar -zxvf - -C verible --strip-components=1
          ls -al ./verible
          ls -al ./verible/bin
          ls -al ./verible/bin/verible-patch-tool
          ls -al ./verible/bin/*
          sudo cp ./verible/bin/* /usr/local/bin
